name: Build & Deployment

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout source repo
        uses: actions/checkout@v3

      # Step 2: Setup pnpm and Node.js
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

      # Step 3: Build the project
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Build the project
        run: npm run build

      # Step 4: Clone the target repository
      - name: Clone target repo
        run: |
          git clone https://github.com/MohammedAltarkawi/test-actions.git target-repo
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Step 5: Copy the specific file to the target repository (create or replace)
      - name: Copy specific file
        run: |
          mkdir -p target-repo/path/deeperFile2/
          cp -r ./dist/vite.svg target-repo/path/deeperFile2/vite.svg

      # Step 6: Commit and push the changes
      - name: Commit and push changes
        run: |
          cd target-repo
          git add path/deeperFile2/vite.svg
          git commit -m "Update or add specific file"
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/MohammedAltarkawi/test-actions.git
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
